---
- name: upgrade | Install Scale object packages
  dnf:
   name: "{{ scale_install_all_packages }}"
   state: latest
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'dnf'
