---
- name: install | Install GPFS HDFS packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_fqdn in scale_hdfs_nodes_list or inventory_hostname in scale_hdfs_nodes_list or ansible_fqdn in scale_protocol_nodes_list or inventory_hostname in scale_protocol_nodes_list


