---
- block:
    - name: create | Find existing filesystem(s)
      shell: /usr/lpp/mmfs/bin/mmvdisk fs list -Y | grep -v HEADER | cut -d ':' -f 7 | uniq
      register: scale_existing_fs
      changed_when: false
      failed_when: false

    - name: create | Create filesystem
      command: "{{ scale_command_path }}mmvdisk fs create --fs {{ item.filesystem }} --vs {{ item.vs }} --mmcrfs -T {{ item.mount_point }}"
      register: scale_fs_create
      failed_when: scale_fs_create.rc != 0
      when:
        - item.filesystem not in scale_existing_fs.stdout_lines
        - item.filesystem is defined
        - item.vs
        - item.mount_point

    - name: create | Waiting for node become active
      shell: "{{ scale_command_path }}mmgetstate -Y | grep active"
      register: scale_gpfs_state
      until: scale_gpfs_state.rc == 0
      retries: 5
      delay: 30
      ignore_errors: True

    - name: create | Mount filesystem
      command: "{{ scale_command_path }}mmmount {{ item.filesystem }} -a"
      register: scale_fs_mount
      failed_when: scale_fs_mount.rc != 0
      when:
        - item.filesystem not in scale_existing_fs.stdout_lines
        - item.filesystem is defined

    - name: create | End of filesystem creation
      debug:
        msg: filesystem {{ item.filesystem }} was successfully created.
      when:
        - item.filesystem not in scale_existing_fs.stdout_lines
        - item.filesystem is defined
  rescue:
    - name: Failure detected during ECE filesystem creation
      fail:
         msg: "I caught an error, Please take a look to the output given!."
