---
- name: install | Disable repo metadata gpg check
  command: "zypper modifyrepo --gpgcheck-allow-unsigned-repo --all"
  args:
    warn: false

- name: install | Install GPFS Callhome packages
  zypper:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: no

- name: install | Enable repo metadata gpg check
  command: "zypper modifyrepo --default-gpgcheck --all"
  args:
    warn: false 

