---
#
# Install or update packages
#
- name: upgrade | Upgrade GPFS HPT packages
  package:
    name: "{{ scale_install_all_packages }}"
    state: latest
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
