---
# tasks file for configure
- name: cluster | env setup
  include_tasks: env_setup.yml
  when: scale_protocols is defined and scale_protocols.hdfs|bool
  tags: config
  loop: "{{ scale_hdfs_clusters }}"

- name: cluster | configure
  include_tasks: configure.yml
  when: scale_protocols is defined and scale_protocols.hdfs|bool
  tags: config
  loop: "{{ scale_hdfs_clusters }}"