---
#
# samples/playbook_remote_mount_cli.yml
#

# Playbook sample for deploying IBM Spectrum Scale (GPFS) cluster with Remote_Mount no GUI on client Cluster
# enabled. Additional variables need to be defined for this, it is recommended
# to use Ansible group variables for this purpose:
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#assigning-a-variable-to-many-machines-group-variables

# Following example will connect up to the first host in your ansible host file, and then run the playbook and do API Call to Storage Cluster.
# So in this case the Client Cluster node need access on https/443 to Storage Cluster GUI Node.

- hosts: host-vm1
  collections:
    - ibm.spectrum_scale
  vars:
    scale_remotemount_storage_gui_username: admin
    scale_remotemount_storage_gui_password: Admin@GUI
    scale_remotemount_storage_gui_hostname: 10.10.10.20
    scale_remotemount_client_no_gui: true
    scale_remotemount_filesystem_name:
      - { scale_remotemount_client_filesystem_name: "fs1", scale_remotemount_client_remotemount_path: "/gpfs/fs1", scale_remotemount_storage_filesystem_name: "gpfs01", } # Minimum variables
      - { scale_remotemount_client_filesystem_name: "fs2", scale_remotemount_client_remotemount_path: "/gpfs/fs1", scale_remotemount_storage_filesystem_name: "gpfs02", scale_remotemount_client_mount_priority: '2', scale_remotemount_access_mount_attributes: "rw", scale_remotemount_client_mount_fs: "yes"  }
  roles:
    - remote_mount
