---
- name: upgrade | Upgrade GPFS SMB packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: latest
   update_only: yes
   disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  register: package_up
  when: ansible_pkg_mgr == 'yum'

- name: upgrade | Upgrade GPFS SMB packages
  package:
    name: "{{ scale_install_all_packages }}"
    state: latest
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
  when: ansible_distribution in scale_rhel_distribution and ansible_distribution_major_version >= '8'
