---
- name: install| Upgrade GPFS nfs packages
  package:
   name: "{{ scale_install_all_packages }}"
   state: latest
  when: scale_install_repository_url is defined

- name: install| Upgrade GPFS NFS deb
  apt:
   deb: "{{ item }}"
   state: latest
  when: scale_install_repository_url is not defined
  with_items:
  - "{{ scale_install_all_packages }}"
